CC = gcc
CFLAGS = -Wall -g -lpthread -lm
TARGET = main
SOURCES = 2.c
OBJECTS = $(SOURCES:.c=.o)

all: $(TARGET)

$(TARGET): $(OBJECTS)
	$(CC) $(CFLAGS) -o $(TARGET) $(OBJECTS)

%.o: %.c 
	$(CC) $(CFLAGS) -c $< -o $@

clean: 
	rm -f $(OBJECTS) $(TARGET)

.PHONY: all clean
